config/routes.rb
Rails.application.routes.draw do
  apipie
  root "home#index"
  get "admin", to: "admins/dashboard#index"

  namespace :admins do
    root "dashboard#index"
    get :dashboard, to: "dashboard#index"

    resources :admins
    resources :accounts
    resources :atc_codes
    resources :countries
    resources :generic_names
    resources :manufactures
    resources :nomenclatures
    resources :items
    resources :recipes
  end

  resources :carts
  resources :orders
  resources :users
end

app/views/admins/_form.html.erb
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.select :role, options_for_select(Admin.roles.map {|key, value| [key.titleize, Admin.roles.key(value)]},
                                              @admin.role) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Active</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.first_name %></td>
        <td><%= admin.last_name %></td>
        <td><%= admin.email %></td>
        <td><%= admin.age %></td>
        <td><%= admin.active %></td>
        <td><%= admin.role %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @admin.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @admin.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @admin.age %>
</p>

<p>
  <strong>Active:</strong>
  <%= @admin.active %>
</p>

<p>
  <strong>Role:</strong>
  <%= @admin.role %>
</p>

<%= link_to 'Edit', edit_admins_admin_path(@admin) %> |
<%= link_to 'Back', admins_admins_path %>