config/routes.rb
Rails.application.routes.draw do
  apipie
  root "home#index"
  get "admin", to: "admins/dashboard#index"

  namespace :admins do
    root "dashboard#index"
    get :dashboard, to: "dashboard#index"

    resources :admins
    resources :accounts
    resources :atc_codes
    resources :countries
    resources :generic_names
    resources :manufactures
    resources :nomenclatures
    resources :items
    resources :recipes
  end

  resources :carts
  resources :orders
  resources :users
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Country < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates_length_of :name, minimum: 3

  has_many :nomenclatures, dependent: :destroy
end

app/controllers/admins/countries_controller.rb
class Admins::CountriesController < ApplicationController
  before_action :set_country, only: %i[ show edit update destroy ]

  # GET /countries or /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1 or /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries or /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to admins_country_url(@country), notice: "Country was successfully created." }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1 or /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to admins_country_url(@country), notice: "Country was successfully updated." }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1 or /countries/1.json
  def destroy
    @country.destroy

    respond_to do |format|
      format.html { redirect_to admins_countries_url, notice: "Country was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_country
    @country = Country.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def country_params
    params.require(:country).permit(:name)
  end
end

app/helpers/admins/countries_helper.rb
module Admins::CountriesHelper
end

app/views/admins/countries/_form.html.erb
<%= form_for [:admins, @country] do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% country.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/countries/edit.html.erb
<h1>Editing ATC Code</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', [:admins, @country]%> |
<%= link_to 'Back', admins_countries_path %>

app/views/admins/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_admins_country_path %>

app/views/admins/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', admins_countries_path %>

app/views/admins/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @country.name %>
</p>

<%= link_to 'Edit', edit_admins_country_path(@country) %> |
<%= link_to 'Back', admins_countries_path %>