config/routes.rb
Rails.application.routes.draw do
  apipie
  root "home#index"
  get "admin", to: "admins/dashboard#index"

  namespace :admins do
    root "dashboard#index"
    get :dashboard, to: "dashboard#index"

    resources :admins
    resources :accounts
    resources :atc_codes
    resources :countries
    resources :generic_names
    resources :manufactures
    resources :nomenclatures
    resources :items
    resources :recipes
  end

  resources :carts
  resources :orders
  resources :users
end

app/controllers/admins/dashboard_controller.rb
class Admins::DashboardController < ApplicationController
end

app/helpers/admins/dashboard_helper.rb
module Admins::DashboardHelper
  def define_admin(role)
    return if role.nil?

    case role.to_sym
    when :admin
      render partial: "admins/dashboard/admin"
    when :pharmacist
      render partial: "admins/dashboard/pharmacist"
    when :physician
      render partial: "admins/dashboard/physician"
    end
  end
end

app/views/admins/dashboard/_admin.html.erb
<h1>Admin</h1>
<%= link_to "Add New Pharmacist/Physician", new_admins_admin_path %>
<%= link_to "Add ATC Code", new_admins_atc_code_path %>
<%= link_to "Add Country", new_admins_country_path %>
<%= link_to "Add Generic Name", new_admins_generic_name_path %>

app/views/admins/dashboard/_pharmacist.html.erb
<h1>Physician</h1>
<%= link_to "Add Item", new_admins_item_path %>

app/views/admins/dashboard/_physician.html.erb
<h1>Pharmacist</h1>
<%= link_to "Add Recipe", new_admins_recipe_path %>

app/views/admins/dashboard/index.html.erb
<%= define_admin(params[:role]) %>