config/routes.rb
Rails.application.routes.draw do
  apipie
  root "home#index"
  get "admin", to: "admins/dashboard#index"

  namespace :admins do
    root "dashboard#index"
    get :dashboard, to: "dashboard#index"

    resources :admins
    resources :accounts
    resources :atc_codes
    resources :countries
    resources :generic_names
    resources :manufactures
    resources :nomenclatures
    resources :items
    resources :recipes
  end

  resources :carts
  resources :orders
  resources :users
end

app/models/atc_code.rb
# == Schema Information
#
# Table name: atc_codes
#
#  id         :bigint           not null, primary key
#  code       :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class AtcCode < ApplicationRecord
  validates :code, :title, presence: true, uniqueness: true
  validates_length_of :title, minimum: 3

  has_many :nomenclatures, dependent: :destroy
end

app/controllers/admins/atc_codes_controller.rb
class Admins::AtcCodesController < ApplicationController
  before_action :set_atc_code, only: %i[ show edit update destroy ]

  # GET /atc_codes or /atc_codes.json
  def index
    @atc_codes = AtcCode.all
  end

  # GET /atc_codes/1 or /atc_codes/1.json
  def show
  end

  # GET /atc_codes/new
  def new
    @atc_code = AtcCode.new
  end

  # GET /atc_codes/1/edit
  def edit
  end

  # POST /atc_codes or /atc_codes.json
  def create
    @atc_code = AtcCode.new(atc_code_params)

    respond_to do |format|
      if @atc_code.save
        format.html { redirect_to admins_atc_code_url(@atc_code), notice: "AtcCode was successfully created." }
        format.json { render :show, status: :created, location: @atc_code }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @atc_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atc_codes/1 or /atc_codes/1.json
  def update
    respond_to do |format|
      if @atc_code.update(atc_code_params)
        format.html { redirect_to admins_atc_code_url(@atc_code), notice: "AtcCode was successfully updated." }
        format.json { render :show, status: :ok, location: @atc_code }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @atc_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atc_codes/1 or /atc_codes/1.json
  def destroy
    @atc_code.destroy

    respond_to do |format|
      format.html { redirect_to admins_atc_codes_url, notice: "AtcCode was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_atc_code
    @atc_code = AtcCode.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def atc_code_params
    params.require(:atc_code).permit(:code, :title)
  end
end

app/helpers/admins/atc_codes_helper.rb
module Admins::AtcCodesHelper
end

app/views/admins/atc_codes/_form.html.erb
<%= form_for [:admins, @atc_code] do |form| %>
  <% if atc_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(atc_code.errors.count, "error") %> prohibited this atc_code from being saved:</h2>

      <ul>
        <% atc_code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/atc_codes/edit.html.erb
<h1>Editing ATC Code</h1>

<%= render 'form', atc_code: @atc_code %>

<%= link_to 'Show',[:admins, @atc_code] %> |
<%= link_to 'Back', admins_atc_codes_path %>

app/views/admins/atc_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ATC Code</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atc_codes.each do |atc_code| %>
      <tr>
        <td><%= atc_code.code %></td>
        <td><%= atc_code.title %></td>
        <td><%= link_to 'Show', [:admins, atc_code] %></td>
        <td><%= link_to 'Edit', edit_admins_atc_code_path(atc_code) %></td>
        <td><%= link_to 'Destroy', [:admins, atc_code], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New ATC Code', new_admins_atc_code_path %>

app/views/admins/atc_codes/new.html.erb
<h1>New ATC Code</h1>

<%= render 'form', atc_code: @atc_code %>

<%= link_to 'Back', admins_atc_codes_path %>

app/views/admins/atc_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @atc_code.code %>
</p>

<p>
  <strong>Title:</strong>
  <%= @atc_code.title %>
</p>

<%= link_to 'Edit', edit_admins_atc_code_path(@atc_code) %> |
<%= link_to 'Back', admins_atc_codes_path %>